name: keepalive
on:
  schedule:
    - cron: "0 22 * * *" # daily, 6am PH time
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://eandj-chi.vercel.app/api/health
